#!/usr/bin/env python3
"""Render the profile READMEs (one per language) from a single template.

Sources live in ``readme/``:
- ``shared.toml``: values common to every language (links, stack, projects, languages);
- ``locales/<code>.toml``: the translated text for one language;
- ``template.md``: the layout, with ``{{ placeholder }}`` references to both.

Usage:
    python3 scripts/build_readme.py          # write every README
    python3 scripts/build_readme.py --check  # exit 1 if a README is out of date (used by CI)

Standard library only (Python 3.11+ for ``tomllib``).
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path
from typing import Any
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
PLACEHOLDER = re.compile(r"\{\{\s*([\w.-]+)\s*\}\}")
MAX_DEPTH = 5
GENERATED_NOTICE = (
    "<!-- Generated by scripts/build_readme.py from readme/: edit those files, not this one. -->"
)


class TemplateError(Exception):
    """A template or locale references something that does not exist."""


# --- Placeholder rendering -------------------------------------------------------------------


def lookup(context: dict[str, Any], path: str) -> Any:
    """Resolve a dotted path such as ``t.about.title`` inside nested dicts."""
    value: Any = context
    for part in path.split("."):
        if not isinstance(value, dict) or part not in value:
            raise TemplateError(f"unknown placeholder {{{{ {path} }}}}")
        value = value[part]
    return value


def to_text(value: Any, path: str) -> str:
    """Turn a resolved value into Markdown: scalars as-is, lists of strings as bullet lists."""
    if isinstance(value, bool) or isinstance(value, dict):
        raise TemplateError(f"placeholder {{{{ {path} }}}} is not text")
    if isinstance(value, list):
        if not all(isinstance(item, str) for item in value):
            raise TemplateError(f"placeholder {{{{ {path} }}}} must be a list of strings")
        return "\n".join(f"- {item}" for item in value)
    return str(value)


def render(text: str, context: dict[str, Any], depth: int = 0) -> str:
    """Replace every ``{{ path }}``; values may contain placeholders themselves."""
    if depth > MAX_DEPTH:
        raise TemplateError("placeholders nested too deeply (is a value referencing itself?)")

    def substitute(match: re.Match[str]) -> str:
        path = match.group(1)
        return render(to_text(lookup(context, path), path), context, depth + 1)

    return PLACEHOLDER.sub(substitute, text)


# --- Generated blocks ------------------------------------------------------------------------


def shields_label(text: str) -> str:
    """Escape text for a shields.io static badge path segment."""
    return quote(text.replace("-", "--").replace("_", "__").replace(" ", "_"), safe="")


def badge(label: str, color: str, logo: str, style: str, logo_color: str = "white") -> str:
    url = (
        f"https://img.shields.io/badge/{shields_label(label)}-{color}"
        f"?style={style}&logo={logo}&logoColor={logo_color}"
    )
    return f'<img src="{url}" alt="{label}"/>'


def language_switcher(languages: list[dict[str, str]], current: str) -> str:
    items = []
    for lang in languages:
        name = f"{lang['flag']} {lang['label']}"
        items.append(f"**{name}**" if lang["code"] == current else f"[{name}](./{lang['file']})")
    return " · ".join(items)


def header_image(shared: dict[str, Any]) -> str:
    header = shared["header"]
    url = (
        "https://capsule-render.vercel.app/api?type=waving"
        f"&color={header['gradient']}&height=180&section=header"
        f"&text={quote(shared['name'])}&fontSize=46&fontColor={header['font_color']}&fontAlignY=38"
        f"&desc={quote(shared['tagline'])}&descSize=16&descAlignY=60"
    )
    return f'<img src="{url}" width="100%" alt="{shared["name"]}"/>'


def stack_badges(stack: list[dict[str, str]], group: str) -> str:
    return "\n".join(
        badge(item["name"], item["color"], item["logo"], "for-the-badge", item.get("logo_color", "white"))
        for item in stack
        if item["group"] == group
    )


def projects_table(shared: dict[str, Any], locale: dict[str, Any]) -> str:
    t = locale["projects"]
    rows = [f"| {t['col_project']} | {t['col_description']} | {t['col_stack']} |", "|---|---|---|"]
    for project in shared["projects"]:
        key = project["key"]
        if project.get("private"):
            name = f"**{key}** <sub>{t['private']}</sub>"
        else:
            name = f"[**{key}**](https://github.com/{shared['github_user']}/{key})"
        rows.append(f"| {name} | {t['descriptions'][key]} | {project['stack']} |")
    return "\n".join(rows)


def build_context(shared: dict[str, Any], locale: dict[str, Any], lang: dict[str, str]) -> dict[str, Any]:
    groups = {item["group"] for item in shared["stack"]}
    return {
        **shared,
        "lang": lang,
        "t": locale,
        "block": {
            "header": header_image(shared),
            "languages": language_switcher(shared["languages"], lang["code"]),
            "stack": {group: stack_badges(shared["stack"], group) for group in groups},
            "projects": projects_table(shared, locale),
        },
    }


# --- Validation ------------------------------------------------------------------------------


def key_paths(table: dict[str, Any], prefix: str = "") -> set[str]:
    paths = set()
    for key, value in table.items():
        path = f"{prefix}{key}"
        paths |= key_paths(value, f"{path}.") if isinstance(value, dict) else {path}
    return paths


def validate(shared: dict[str, Any], locales: dict[str, dict[str, Any]]) -> list[str]:
    """Every language must translate exactly the same keys, including every project."""
    errors = []
    codes = [lang["code"] for lang in shared["languages"]]
    if len(set(codes)) != len(codes):
        errors.append("duplicate language code in shared.toml")
    reference_code = codes[0]
    reference = key_paths(locales[reference_code])
    for code in codes:
        keys = key_paths(locales[code])
        for missing in sorted(reference - keys):
            errors.append(f"locales/{code}.toml: missing {missing}")
        for extra in sorted(keys - reference):
            errors.append(f"locales/{code}.toml: {extra} is not in locales/{reference_code}.toml")
        descriptions = locales[code].get("projects", {}).get("descriptions", {})
        for project in shared["projects"]:
            if project["key"] not in descriptions:
                errors.append(f"locales/{code}.toml: no description for project {project['key']}")
    return errors


# --- I/O -------------------------------------------------------------------------------------


def load(root: Path) -> tuple[dict[str, Any], dict[str, dict[str, Any]], str]:
    source = root / "readme"
    shared = tomllib.loads((source / "shared.toml").read_text(encoding="utf-8"))
    locales = {}
    for lang in shared["languages"]:
        path = source / "locales" / f"{lang['code']}.toml"
        if not path.exists():
            raise TemplateError(f"missing {path.relative_to(root)}")
        locales[lang["code"]] = tomllib.loads(path.read_text(encoding="utf-8"))
    template = (source / "template.md").read_text(encoding="utf-8")
    return shared, locales, template


def build(root: Path) -> dict[Path, str]:
    """Return the rendered content of every README, keyed by output path."""
    shared, locales, template = load(root)
    errors = validate(shared, locales)
    if errors:
        raise TemplateError("\n".join(errors))
    outputs = {}
    for lang in shared["languages"]:
        body = render(template, build_context(shared, locales[lang["code"]], lang))
        outputs[root / lang["file"]] = f"{GENERATED_NOTICE}\n{body.rstrip()}\n"
    return outputs


def main(argv: list[str] | None = None, root: Path = ROOT) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if a README is out of date")
    args = parser.parse_args(argv)
    try:
        outputs = build(root)
    except (TemplateError, KeyError, tomllib.TOMLDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(root)} (run python3 scripts/build_readme.py)", file=sys.stderr)
        return 1 if stale else 0
    for path in stale:
        path.write_text(outputs[path], encoding="utf-8")
        print(f"wrote {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
